### PR TITLE
Handle RX buffer allocation failure; TX queue full as debug message

### PR DESCRIPTION
**Pull request by joft-mle**
Hi Alex,

we have created this pull request against your "staging" repository, since the changes of the first commit (at least) concern locations, which have been changed in your staging repository versus the official cordundum repository.

In this small number of patches, we introduce

* the possibility to let RX buffer allocation fail and output a hint for the user on how to proceed
* turning the "TX ring full" message into a debug message, which can be made visible on-demand (given dynamic debug support in the kernel)

### CODE REVIEW

**Comment by joft-mle** [comment]
Now that this repository's master branch has been merged into the official corundum repository, do you want us to rebase and re-open a pull request there? Or shall we keep handling this pull request 2 here?

**Comment by alexforencich** [comment]
I really need to figure out a better way to handle bleeding edge dev vs. staging vs. stable.  Right now, I am using this repo for bleeding edge stuff (lots of rebases, force pushes, etc.), the ucsdsysnet repo as a staging repo (should be relatively stable, but occasionally might get a force push), and the corundum repo as the "stable" repo (things are only pushed after a reasonable level of testing).  I should probably be doing this with branches on the main repo, but tbh I'm far from an expert at using git and don't have branches figured out yet.  Anyway, I think rebasing and moving this to either the main corundum repo or the sysnet repo would be better than here.  But, I will also do some reading and see if I can figure out how to use branches properly.

**Comment by joft-mle** [comment]
Ok, understood, we will rebase and re-post on the main corundum repository.

**Comment by alexforencich** [comment]
Also, what about doing something along the lines of printk_ratelimited?

**Comment by alexforencich** [comment]
Perhaps a simpler option could be similar to netdev_*_once, but perhaps clear the flag periodically

**Comment by joft-mle** [comment]
This pull request is obsoleted by the following new pull request against the main corundum repository:  https://github.com/corundum/corundum/pull/155

**Pull request closed without merging**
